# TEST Environment
project_id = "xvuugxjseavbxpxhfprb"

[functions.generate-weekly-schedules]
verify_jwt = false

[functions.optimize-base-schedule-milp]
verify_jwt = false

[functions.optimize-base-schedule-milp-scenario]
verify_jwt = false

[functions.optimize-planning-milp]
verify_jwt = false

[functions.generate-planning-pdf]
verify_jwt = false

[functions.validate-planning]
verify_jwt = false

[functions.optimize-planning-milp-orchestrator]
verify_jwt = false

[functions.optimize-planning-milp-bloc]
verify_jwt = false

[functions.optimize-planning-milp-sites]
verify_jwt = false

[functions.optimize-planning-milp-flexible]
verify_jwt = false

[functions.assign-closing-responsibles]
verify_jwt = false