project_id = "xvuugxjseavbxpxhfprb"

[functions.generate-planning-pdf]
verify_jwt = false

[functions.validate-planning]
verify_jwt = false

[functions.assign-closing-responsibles]
verify_jwt = false

[functions.optimize-secretary-assignments-v2]
verify_jwt = false