project_id = "xvuugxjseavbxpxhfprb"

[functions.generate-weekly-schedules]
verify_jwt = false

[functions.optimize-base-schedule-milp]
verify_jwt = false

[functions.optimize-planning-milp]
verify_jwt = false